services:
  MagicMike\ApiVersioning\Profiler\ApiVersionDataCollector:
    arguments:
      $headerName: '%api_versioning.header_name%'
      $provider: '@MagicMike\ApiVersioning\Contract\ApiVersionProviderInterface'
    tags:
      - { name: kernel.event_subscriber }
      - { name: data_collector, id: 'MagicMike\ApiVersioning\Profiler\ApiVersionDataCollector', priority: 255 }
