services:
  MagicMike\ApiVersioning\Provider\DefaultApiVersionProvider:
    arguments:
      - !tagged_iterator api_versioning.version

  MagicMike\ApiVersioning\Resolver\DefaultApiVersionResolver:
    arguments:
      $headerName: '%api_versioning.header_name%'

  MagicMike\ApiVersioning\Manager\ApiVersionEventManager:
    arguments:
      $provider: '@MagicMike\ApiVersioning\Provider\DefaultApiVersionProvider'
      $resolver: '@MagicMike\ApiVersioning\Resolver\DefaultApiVersionResolver'
      $eventDispatcher: '@event_dispatcher'

  MagicMike\ApiVersioning\EventListener\ApiVersioningKernelListener:
    arguments:
      $manager: '@MagicMike\ApiVersioning\Manager\ApiVersionEventManager'
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: 0 }

  MagicMike\ApiVersioning\Contract\ApiVersionProviderInterface:
    alias: MagicMike\ApiVersioning\Provider\DefaultApiVersionProvider

  MagicMike\ApiVersioning\Contract\ApiVersionResolverInterface:
    alias: MagicMike\ApiVersioning\Resolver\DefaultApiVersionResolver